name: Tweak Cloud Compiler

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          # التنصيب في المجلد المحلي للمشروع بدلاً من /opt/
          export THEOS=$GITHUB_WORKSPACE/theos
          mkdir -p $THEOS
          
          sudo apt-get update
          sudo apt-get install -y clang make git perl debianutils
          
          # تحميل Theos في مسار العمل
          git clone --depth 1 https://github.com/theos/theos $THEOS
          
          # تحميل الـ SDKs
          mkdir -p $THEOS/sdks
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks
          
          # إعداد dm.pl
          curl -L https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl -o $THEOS/bin/dm.pl
          chmod +x $THEOS/bin/dm.pl
          
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH

      - name: Compile
        run: |
          # تأكد أن اسم المجلد بالأسفل يطابق اسم المجلد في مستودعك
          cd iOS-Simple-IGG-Mod-Menu-main
          make clean
          make package FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tweak-package
          path: iOS-Simple-IGG-Mod-Menu-main/packages/*.deb
